### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/sprouts#38]
I think the documentation could be improved a bit. In my opinion it's not always clear what the behavior is and what we can expect.
Maybe we can discuss the unclear parts here.

**Comment by Mazi-S** [comment]
One thing that is not entirely clear to me is when a factory method `.of(...)` or `.ofNullable(...)` creates a live view or just a copy of the current value.

If I look at the following factory methods in `Val`:

```Java
static <T> Val<T> of(
    Val<T> toBeCopied
)
```
```Java
static <T extends @Nullable Object> Val<@Nullable T> ofNullable(
    Val<T> toBeCopied
)
```

It's quite clear that only the value of the property is copied (although this is not mentioned in the documentation and I think we should add this information).

On the other hand, the following factory methods in `Val` create a live view of two given `Val`:
```Java
static <T> Val<T> of(
    Val<T> first,
    Val<T> second,
    BiFunction<T, T, T> combiner
)
```
```Java
static <T extends @Nullable Object> Val<@Nullable T> ofNullable(
    Val<T> first,
    Val<T> second,
    BiFunction<T, T, T> combiner
)
```

Maybe we should rename the methods that create a live view... We could use `viewOf` or something other than `of`, `ofNullable`.

When we talk about property lists, things get a little confusing. For example, the `of(...)` method in `Vals` does not copy the value like the `of(...)` method in `Val`. It adds the property itself and changes are reflected.

```Java
static <T> Vals<T> of(
    Val<T> first,
    Val<T>... rest
)
``` 

So I think we should at least add a comment to each factory method to clarify if changes are reflected or not.

**Comment by Gleethos** [comment]
I completely agree that when it comes to the factory methods taking in other properties,
it should be stated explicitly that only the value is copied simply due to the fact that we are
working with wrapper types here. One could easily operate under the assumption
that the provided property is simply delegated instead of being excavated.

I also like the suggestion of renaming the `of(Val,Val,BiFunction)` factory to `viewOf`.
This would make it much more consistent with the rest of the view methods
like `viewSize`, `viewIsEmpty`, `viewAs(..)`...
And it would distinguish it from the other factory methods in a meaningful way.

But this should not be done under this ticket.
Either #39, or a new one...

Additionally to the formerly mentioned suggestions,
I think we can also introduce the improvements from #39 
here. So more specifically I think it makes sense that 
for each primitive + non-null view method we should mention that, the user is allowed to map null references to
something other than null, but if they don't, we take over and map to the respective null object.
