### ISSUE TITLE
Improve view and viewAs methods

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/sprouts#39]
Maybe we should introduce a `viewAsNullable` in addition to `viewAs`.
This would make it consistent with the current API (`of(...)` and `ofNullable(...)`) and we could ensure that the `viewAs` method never returns a nullable. Currently we can't guarantee this.

What do you think @Gleethos?

**Comment by Gleethos** [comment]
I 100% agree! This should be explicit for nullability and it would make things consistent with the factory methods. (in a sense, `viewAs` is also a factory method)

**Comment by Mazi-S** [comment]
The non-nullable version (`viewAs`) can now map `null` to any kind of value and not necessarily to the default value (e.g. not the empty string for `String`).
Perhaps we should consider introducing another `viewAs` method that also takes a default value to use when the viewed property is null. So if the property is empty, the view is equal to the provided default value, otherwise the mapping function is applied.

```Java
Var<Integer> var = ...
Val<String> val = var.viewAs(String.class, i => "int==" + i, "");
```

But I don't know if this would be a good extension.

**Comment by Mazi-S** [comment]
I found a discrepancy between the documentation and the spec (tests).

Documentation of `Val.viewAsInt`
> Note that null references inside the viewed property will always be mapped to the "null object" of the Integer type, which is 0.

And the test `Map null to custom values when viewing them as primitive types.` in `Viewing_Properties_Spec.groovy` says something else...

**Comment by Gleethos** [comment]
I did some thinking with respect to the following suggestion:
```java
Var<Integer> var = ...
Val<String> val = var.viewAs(String.class, i => "int==" + i, "");
```
I think there are 2 big improvements for the method signature.

1.: We should have the mapping function always at the end of the argument list.
This is because it makes multi-line mapping functions less akward:
```java
var.viewAs(String.class, i => {
        String a = parseA(i);
        String b = parseB(i);
        return a + " - " + b;
    }, 
    "default value" // <- akward
);
```
**VS**
```java
var.viewAs(String.class, "default value", i => {
        String a = parseA(i);
        String b = parseB(i);
        return a + " - " + b;
    });
```

2.: Since this is the null safe variant we should operate under the assumption
that **the default value is never null**.
This then **allows us to always get the correct type class from the default value**.
So I believe we can effectively reduce the method signature to the following:
```java
var.viewAs("default value", i => {
        String a = parseA(i);
        String b = parseB(i);
        return a + " - " + b;
    });
```

---

> I found a discrepancy between the documentation and the spec (tests).

In this case the unit test is more correct than the method documentation.
The `view` based methods are different from the `map` methods in the sense that
they try to be more open about what the user is actually working with, whereas
the `mapping` methods are, like with an optional, there to work with properties
in a null safe manner...

So in case of the `viewAsInt`, **the user is allowed to map null references to
something other than null, but if they don't, we take over and map to the int's null object: `0`.**

But yeah I agree, the documentation is misleading/incomplete here! That should be fixed too.

**Comment by Mazi-S** [comment]
What do you think about introducing a `viewAsInt(defaultValue, mapper)` which maps `null` to the `defaultValue` and non-null values to the mapped value?
And the `viewAsInt(mapper)` is equal to `viewAsInt(0, mapper)`.

This would make the `viewAsInt`, `viewAsString`, ... methods similar to the `viewAs` method.

**Comment by Mazi-S** [comment]
If we introduce `viewAs( U defaultValue, Function<T, U> mapper );`, then `viewAs( Integer.class, v -> 1);` cannot be resolved because the method call is ambiguous (we would have to cast the lambda to `Function<T, Integer>`, which is not nice).

I don't know if there is a good solution...

**Comment by Gleethos** [comment]
> What do you think about introducing a viewAsInt(defaultValue, mapper) which maps null to the defaultValue and non-null values to the mapped value?

Oh, I really like this idea because that way the user can decide
for themselves what the null object for a particular view should be!
We can then also reference the method and default value the view ultimately resolves
to in the documentation. 
It's super transparent to the user when `viewAsInt(mapper)` is just short hand for `viewAsInt(0, mapper)`.
We should definitely do that. Thank you for the proposal. 

> I don't know if there is a better solution...

I went through the `Val` class and noticed/remembered that in the context 
of it's API, the `As` in `viewAs` refers to the first parameter being the **target type**!
The word **'as' implies that a type is being supplied**...
So when creating a view which maps to the same type,
the following method exists for that exact purpose:
```java
default Val<T> view( Function<T, T> mapper ) {
    return viewAs( type(), mapper );
}
```
As you can see, the `As` is omitted because it is not
mapped to another type...

Based on that distinction, I suggest we introduce the new method 
with the signature:
```java
view( U defaultValue, Function<T, U> mapper );
```
...instead of:
```java
viewAs( Class<U> type, U defaultValue, Function<T, U> mapper );
```

That way we don't get ambiguities both syntactically and semantically.

**Comment by Mazi-S** [comment]
I really like your suggestion.

One inconsistency I still see with the view methods is that `view( U nullObject, Function<T, U> mapper )` maps null values of the viewed property directly to the `nullObject` and the mapping function is not allowed to produce a null value.
The `viewAsInt( int nullObject, Function<T, @Nullable Integer> mapper )` passes null values to the mapper and maps the result to the `nullObject` if it is null.

At least it is documented now, but perhaps we should consider changing the behavior of the `view` method to match the behavior of `viewAsInt`.

**Comment by Gleethos** [comment]
> At least it is documented now, but perhaps we should consider changing the behavior of the view method to match the behavior of `viewAsInt`.

Yeah I agree! But is the behaviour not already consistent?
I looked at the code and it looks like the mapper is always called, even if the value is null.
So the user always has the option to map any received `null` value to an alternative.
Or do you mean something else?

**Comment by Mazi-S** [comment]
The current implementation of the `view` method only maps if a value is present: [AbstractVariable.view](https://github.com/globaltcad/sprouts/blob/5d3e61dad9f6c29c5e0997f70973a93be3570451/src/main/java/sprouts/impl/AbstractVariable.java#L187)

**Comment by Gleethos** [comment]
Then I would say that is incorrect.
It should map the value, irrespective of what it is,
and then in case of it being null after mapping, the value
should be resolved to a `null object`/`default value` if 
one is present or it makes sense for a particular type...

**Comment by Mazi-S** [comment]
The `view` method now behaves similarly to all other view methods. We can reuse it almost everywhere now.
One thing I noticed is that the `viewAsDouble` method has a specific error value (`Double.NaN`) when an exception occurs.
We may want to introduce a `view` method that does the same thing: 
```Java
view(nullObject, errorObject, mapper)
```
Otherwise we won't be able to distinguish between an error and `null`.

**Comment by Gleethos** [comment]
That sounds like a really great idea! The `viewAsDouble` case really
highlights that problem where the type itself also has a state representing the occurrence of an error!
A user of the API may not only want to use a custom null object for their types, but
also resort to the practice of having an instance representing erroneous state.

I am all for it!

Not sure about the method name. But I also have nothing against `view`...
